server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/simpledemo.p12
    key-store-password: simpledemo.sp
    key-alias: simpledemo
    enabled: false #Here to turn on/off https
  port: 8001
  tomcat:
    uri-encoding: UTF-8
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    propagation:
      type: w3c
      consume: w3c
      produce: w3c
    enabled: true
    baggage:
      correlation:
        enabled: true
      remote-fields: traceId,spanId,traceparent,tracestate

spring:
  application:
    name: simple-gateway
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
    kubernetes:
      enabled: false
    gateway:
      routes:
        - id: my_service_route
          uri: http://localhost:18888/ #try http://localhost:8001/api/mongo/higet?par=v123 will goto: http://localhost:18888/api/mongo/higet?par=v123
          predicates:
            - Path=/** #
          filters:
            - AddRequestHeader=X-Request-Foo, bar #
---

spring:
  config:
    activate:
      on-profile: dev

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true
      limitForPeriod: 1 #The number of permissions available during one limit refresh period
      limitRefreshPeriod: 1s #The period of a limit refresh. After each period the rate limiter sets its permissions count back to the limitForPeriod value
      timeoutDuration: 0 #The default wait time a thread waits for a permission
      eventConsumerBufferSize: 100
  instances:
    backendA:
      baseConfig: default
    backendB:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: false
      timeoutDuration: 2s
  instances:
    backendA:
      baseConfig: default
    backendB:
      baseConfig: default

